import streamlit as st

AZURE_TENANT_ID = st.secrets["AZURE_TENANT_ID"]
AZURE_APP_ID = st.secrets["AZURE_APP_ID"] 
AZURE_CLIENT_SECRET = st.secrets["AZURE_CLIENT_SECRET"]
AZURE_STORAGE_NAME = st.secrets["AZURE_STORAGE_NAME"]
GOLEMIO_TOKEN = st.secrets["GOLEMIO_TOKEN"]